{% set name = "mdformat-gfm" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat_gfm-{{ version }}.tar.gz
  sha256: d1d49a409a6acb774ce7635c72d69178df7dce1dc8cdd10e19f78e8e57b72623

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2.0,<4
    - pip
  run:
    - python >={{ python_min }}
    - mdformat >=0.7.5,<0.8.0
    - markdown-it-py
    - mdit-py-plugins >=0.2.0
    - mdformat-tables >=0.4.0

test:
  imports:
    - mdformat_gfm
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Mdformat plugin for GitHub Flavored Markdown compatibility
  home: https://github.com/hukkin/mdformat-gfm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anjos
